services:
  - type: web
    name: ashab-almaher
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi --bind 0.0.0.0:$PORT --timeout 120 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.5"
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
